### PR TITLE
Turkish language added

### PR DESCRIPTION
**Pull request by ooguz**
Hello,

I translated Carnet into Turkish, now I'm going to translate Carnet documentation. After a while I'm planning to revise translations.

Thank you, have a nice day!

Sincerely,

### CODE REVIEW

**Comment by PhieF** [comment]
Oups sorry didn't see this ! Thanks !

Would it be possible to remove the array file ? This one shouldn't be translated ! Thank you again

**Comment by ooguz** [comment]
Hello again,

I removed the array file, you can merge it!

**Comment by PhieF** [comment]
Perfect !! Thank you

**Comment by PhieF** [comment]
BTW you can now use this platform for translation

https://weblate.lostpod.me

**Comment by ooguz** [comment]
I saw that link on repo but at that date it was not working :) I will open a PR for other repos (Documentation etc.) in a couple days btw

**Comment by PhieF** [comment]
Yes it was broken

I will merge the other also, thx again !

**Pull request merged**
